variables:
  CI_IMAGE: registry.ddbuild.io/images/docker:20.10.13
  RESTORE_CACHE_ATTEMPTS: 2
  BUILD_STABLE_REGISTRY: '486234852809.dkr.ecr.us-east-1.amazonaws.com'

stages:
  - build

# =======================================================================
# Build and deploy the images used for CI
# =======================================================================

.build-ci-image: &build-ci-image
  stage: build
  tags: ["runner:docker"]
  image: $CI_IMAGE
  script:
    - TAG="v$CI_COMMIT_SHORT_SHA-$IMAGE_TAG_SUFFIX"
    - docker build --file $DOCKERFILE --tag registry.ddbuild.io/ci/opentelemetry-demo:$TAG --label target=staging .
    - docker push registry.ddbuild.io/ci/opentelemetry-demo:$TAG

build-ci-image-adservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/adservice/Dockerfile
    IMAGE_TAG_SUFFIX: adservice

build-ci-image-cartservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/cartservice/src/Dockerfile
    IMAGE_TAG_SUFFIX: cartservice

build-ci-image-checkoutservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/checkoutservice/Dockerfile
    IMAGE_TAG_SUFFIX: checkoutservice

build-ci-image-currencyservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/currencyservice/Dockerfile
    IMAGE_TAG_SUFFIX: currencyservice


build-ci-image-emailservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/emailservice/Dockerfile
    IMAGE_TAG_SUFFIX: emailservice

build-ci-image-featureflagservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/featureflagservice/Dockerfile
    IMAGE_TAG_SUFFIX: featureflagservice

build-ci-image-frontend:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/frontend/Dockerfile
    IMAGE_TAG_SUFFIX: frontend

build-ci-image-frontendproxy:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/frontendproxy/Dockerfile
    IMAGE_TAG_SUFFIX: frontendproxy

build-ci-image-loadgenerator:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/loadgenerator/Dockerfile
    IMAGE_TAG_SUFFIX: loadgenerator

build-ci-image-paymentservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/paymentservice/Dockerfile
    IMAGE_TAG_SUFFIX: paymentservice

build-ci-image-productcatalogservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/productcatalogservice/Dockerfile
    IMAGE_TAG_SUFFIX: productcatalogservice

build-ci-image-quoteservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/quoteservice/Dockerfile
    IMAGE_TAG_SUFFIX: quoteservice

build-ci-image-recommendationservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/recommendationservice/Dockerfile
    IMAGE_TAG_SUFFIX: recommendationservice

build-ci-image-shippingservice:
  <<: *build-ci-image
  variables:
    DOCKERFILE: src/shippingservice/Dockerfile
    IMAGE_TAG_SUFFIX: shippingservice
