receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, jaeger ]
