---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
    component: otel-demo-productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
      component: otel-demo-productcatalogservice
  template:
    metadata:
      labels:
        team: team-opentelemetry
        service: productcatalogservice
        app: productcatalogservice
        component: otel-demo-productcatalogservice
    spec:
      containers:
      - name: productcatalogservice
        image:  otel/demo:v0.2.0-alpha-productcatalogservice
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 200m
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
               apiVersion: v1
               fieldPath: status.podIP
        - name: OTEL_RESOURCE
          value: k8s.pod.ip=$(MY_POD_IP)
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          
        - name: OTEL_AGENT_ENDPOINT
          value: "$(HOST_IP)"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(OTEL_AGENT_ENDPOINT):4318"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(OTEL_AGENT_ENDPOINT):4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=productcatalogservice,deployment.environment=staging"
        - name: PRODUCT_CATALOG_SERVICE_PORT
          value: "3550"

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
    component: otel-demo-productcatalogservice
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: productcatalogservice
    component: otel-demo-productcatalogservice
---
