agents:
  image:
    tagSuffix: jmx
datadog:
  logs:
    enabled: true
  tags:
    - "env:otel-ingest"
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
