# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlp/instana:
    endpoint: "{env:INSTANA_AGENT_HOST}:4317"
    tls:
      insecure: true
  # instana:
  #   # loglevel: debug
  #   endpoint: https://serverless-orange-saas.instana.io
  #   agent_key: <insert your agent key>
  #   tls:
  #     insecure_skip_verify: true
  instana:
    endpoint: https://instana.tec.cz.ibm.com/serverless
    agent_key: vzWTqejpZuXVqwUYWeKcFy
    tls:
      insecure_skip_verify: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
  # temporary measure until description is fixed in .NET
  transform:
    metric_statements:
      - context: metric
        statements:
          - set(description, "Measures the duration of inbound HTTP requests") where name == "http.server.duration"
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      # exporters: [logging, otlp/jaeger, otlp/instana, instana]
      # exporters: [logging, otlp/jaeger, otlp/instana]
      exporters: [logging, otlp/jaeger, instana]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging, otlp/instana]
      processors: [filter, transform, batch]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
