receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlp/instana:
    endpoint: "{env:INSTANA_AGENT_HOST}:4317"
    tls:
      insecure: true
  # instana:
  #   # loglevel: debug
  #   endpoint: https://serverless-orange-saas.instana.io
  #   agent_key: <insert your agent key>
  #   tls:
  #     insecure_skip_verify: true
  instana:
    endpoint: https://instana.tec.cz.ibm.com/serverless
    agent_key: vzWTqejpZuXVqwUYWeKcFy
    tls:
      insecure_skip_verify: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      # exporters: [logging, otlp/jaeger, otlp/instana, instana]
      # exporters: [logging, otlp/jaeger, otlp/instana]
      exporters: [logging, otlp/jaeger, instana]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging, otlp/instana]
