# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file


# Azure Monitor Exporter Configuration
#receivers:
#  otlp:
#    protocols:
#      grpc:

exporters:
  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track" # Azure Monitor Default
    instrumentation_key: "80fe2786-859b-4617-acf6-57b9e0e64392" # My App Insights 
    
#processors:
#  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, spanmetrics]
#    metrics:
#      receivers: [spanmetrics]
#      exporters: [azuremonitor]
