# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  logging:

processors:
  batch:
    filter/ottl:
      error_mode: ignore
      metrics:
        metric:
          # FIXME: remove when a Metrics View is implemented in the checkout and productcatalog components
          # or when this issue is resolved: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3071
          - 'name == "rpc.server.duration"'
    transform:
      metric_statements:
        - context: metric
          statements:
            # FIXME: remove when this issue is resolved: https://github.com/open-telemetry/opentelemetry-java/issues/4834
            - set(description, "") where name == "queueSize"
            # FIXME: remove when these 2 issues are resolved:
            # Java: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9478
            # Go: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4301
            - set(description, "") where name == "rpc.server.duration"
            # FIXME: remove when this issue is resolved: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1958
            - set(description, "") where name == "http.client.duration"

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter/ottl, transform, batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
