name: "Build"

on:
  pull_request:
    types: [opened]

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      DOCKERHUB_REPO: "otel/demo"
      GHCR_REPO: "ghcr.io/open-telemetry/demo"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: prepare build env
        run: make build-env-file

      - name: build and push ghcr docker image
        run: make build-and-push-ghcr

      - name: build and push dockerhub image
        run: make build-and-push-dockerhub
