name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Images
        run: |
          docker buildx build --platform linux/amd64 -t iscanprint/accountingservice:3.0 ./src/accountingservice/
          docker buildx build --platform linux/amd64 -t iscanprint/adservice:3.0 ./src/adservice/
          docker buildx build --platform linux/amd64 -t iscanprint/cartservice:3.0 ./src/cartservice/src/
          docker buildx build --platform linux/amd64 -t iscanprint/checkoutservice:3.0 ./src/checkoutservice/
          docker buildx build --platform linux/amd64 -t iscanprint/currencyservice:3.0 ./src/currencyservice/
          docker buildx build --platform linux/amd64 -t iscanprint/emailservice:3.0 ./src/emailservice/
          docker buildx build --platform linux/amd64 -t iscanprint/frauddetectionservice:3.0 ./src/frauddetectionservice/
          docker buildx build --platform linux/amd64 -t iscanprint/frontend:3.0 ./src/frontend/
          docker buildx build --platform linux/amd64 -t iscanprint/frontendproxy:3.0 ./src/frontendproxy/
          docker buildx build --platform linux/amd64 -t iscanprint/imageprovider:3.0 ./src/imageprovider/
          docker buildx build --platform linux/amd64 -t iscanprint/kafka:3.0 ./src/kafka/
          docker buildx build --platform linux/amd64 -t iscanprint/loadgenerator:3.0 ./src/loadgenerator/
          docker buildx build --platform linux/amd64 -t iscanprint/paymentservice:3.0 ./src/paymentservice/
          docker buildx build --platform linux/amd64 -t iscanprint/productcatalogservice:3.0 ./src/productcatalogservice/
          docker buildx build --platform linux/amd64 -t iscanprint/quoteservice:3.0 ./src/quoteservice/
          docker buildx build --platform linux/amd64 -t iscanprint/recommendationservice:3.0 ./src/recommendationservice/
          docker buildx build --platform linux/amd64 -t iscanprint/shippingservice:3.0 ./src/shippingservice/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          docker push iscanprint/accountingservice:3.0
          docker push iscanprint/adservice:3.0
          docker push iscanprint/cartservice:3.0
          docker push iscanprint/checkoutservice:3.0
          docker push iscanprint/currencyservice:3.0
          docker push iscanprint/emailservice:3.0
          docker push iscanprint/frauddetectionservice:3.0
          docker push iscanprint/frontend:3.0
          docker push iscanprint/frontendproxy:3.0
          docker push iscanprint/imageprovider:3.0
          docker push iscanprint/kafka:3.0
          docker push iscanprint/loadgenerator:3.0
          docker push iscanprint/paymentservice:3.0
          docker push iscanprint/productcatalogservice:3.0
          docker push iscanprint/quoteservice:3.0
          docker push iscanprint/recommendationservice:3.0
          docker push iscanprint/shippingservice:3.0
