name: CI/CD Pipeline by Fortress Technologies Inc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker_build_push() {
            service_name=$1
            dockerfile=$2
            docker_tag=iscanprint/${service_name}:3.0

            docker build -t $docker_tag -f $dockerfile .
            docker push $docker_tag
            docker rmi -f $docker_tag
          }

          services=(
            "accountingservice src/accountingservice/Dockerfile"
            "adservice otp/src/adservice/Dockerfile"
            "cartservice otp/src/cartservice/src/"
            "checkoutservice otp/src/checkoutservice/"
            "currencyservice otp/src/currencyservice/"
            "emailservice otp/src/emailservice/"
            "frauddetectionservice otp/src/frauddetectionservice/"
            "frontend otp/src/frontend/"
            "frontendproxy otp/src/frontendproxy/"
            "imageprovider otp/src/imageprovider/"
            "kafka otp/src/kafka/"
            "loadgenerator otp/src/loadgenerator/"
            "paymentservice otp/src/paymentservice/"
            "productcatalogservice otp/src/productcatalogservice/"
            "quoteservice otp/src/quoteservice/"
            "recommendationservice src/recommendationservice/"
            "shippingservice otp/src/shippingservice/"
          )

          for service in "${services[@]}"; do
            service_name=$(echo $service | cut -d ' ' -f 1)
            service_path=$(echo $service | cut -d ' ' -f 2)
            docker_build_push $service_name $service_path
          }
