# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "Create a Release"

on:
  release:
    types: [published]

jobs:
  build_and_push_images:
    uses: ./.github/workflows/build-images.yml
    with:
      push: true
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
