# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "Create a Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: version tag for container images
        default: 0.0.1
        required: false
        type: string

jobs:
  build_and_push_images:
    uses: ./.github/workflows/build-images.yml
    with:
      push: true
      version: ${{ inputs.version }}
    secrets: inherit
