name: "Release"

on:
  release:
    types: [published]
  pull_request:
    branches: [ main ] # for debug, pls remove this

jobs:
  docker_build_matrix:
    strategy:
      matrix:
        file_tag:
          - file: ./src/adservice/Dockerfile
            tag: adservice
          - file: ./src/cartservice/src/Dockerfile
            tag: cartservice
          - file: ./src/checkoutservice/Dockerfile
            tag: checkoutservice
          - file: ./src/currencyservice/Dockerfile
            tag: currencyservice
          - file: ./src/emailservice/Dockerfile
            tag: emailservice
          - file: ./src/frontend/Dockerfile
            tag: frontend
          - file: ./src/paymentservice/Dockerfile
            tag: paymentservice
          - file: ./src/productcatalogservice/Dockerfile
            tag: productcatalogservice
          - file: ./src/quoteservice/Dockerfile
            tag: quoteservice
          - file: ./src/shippingservice/Dockerfile
            tag: shippingservice
          - file: ./src/featureflagservice/Dockerfile
            tag: featureflagservice
          - file: ./src/loadgenerator/Dockerfile
            tag: loadgenerator
          - file: ./src/recommendationservice/Dockerfile
            tag: recommendationservice
          - file: ./src/frontend/Dockerfile.cypress
            tag:  frontend-tests
          - file: ./test/Dockerfile
            tag: integrationTests
  build_and_push_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      DOCKERHUB_REPO: "otel/demo"
      GHCR_REPO: "ghcr.io/open-telemetry/demo"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # limit docker push image concurrency to 1
      # to avoid github package return 429 ratelimit error
      - name: Set docker upload concurrent
        run: |
          echo $'{"max-concurrent-uploads": 1}' | sudo dd status=none of=/etc/docker/daemon.json
          sudo service docker restart

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Matrix Build and push demo images
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./
          file: ${{ matrix.file_tag.file }}
          platforms: linux/amd64,linux/arm64
          #push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.RELEASE_VERSION }},${{ env.GHCR_REPO }}:${{ env.RELEASE_VERSION }},
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: prepare build env
        run: make build-env-file

      - name: build and push ghcr docker image
        run: make build-and-push-ghcr

      - name: build and push dockerhub image
        run: make build-and-push-dockerhub
