# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Integration Tests

on:
  workflow_run:
    workflows: ["Checks"]
    types:
      - completed

jobs:
  build_runner:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: metal-runner-action
        uses: equinix-labs/metal-action-runner@v0.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          metal_auth_token: ${{ secrets.METAL_AUTH_TOKEN }}
          metal_project_id: ${{ secrets.METAL_PROJECT_ID }}
          metro: "da"
          plan: "c3.small.x86"
          os: "ubuntu_20_04"
  run_tests:
    needs: build_runner
    runs-on: self-hosted
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: run tracetesting
        run: |
          make run-tracetesting
  destroy:
    needs: [build_runner, run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: metal-sweeper-action
        uses: equinix-labs/metal-action-sweeper@v0.6.0
        with:
          authToken: ${{ secrets.METAL_AUTH_TOKEN }}
          projectID: ${{ secrets.METAL_PROJECT_ID }}
          keepProject: true
