# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Integration Tests

on:
  pull_request_review:
    types:
      - submitted

jobs:
  run_tests:
    runs-on: otel-linux-arm64
    name: "Run CI"
    if: github.event.review.state == 'APPROVED'
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: run tracetesting
        run: |
          make build && make run-tracetesting
