# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Integration Tests

on:
  workflow_call:
  pull_request_review:
    types: [submitted]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: "Run CI"
    if: github.event.review.state == 'approved'
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: install docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - name: run tracetesting
        run: |
          make build && make run-tracetesting
